// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Realtime Database URL (must match Firebase console → Realtime Database).
  static const String firebaseRtdbUrl = 'https://kidguard-fadf9-default-rtdb.firebaseio.com';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwf-g2AydH4u0QzGxiqdqMbIgkADSA4Uo',
    appId: '1:1002940114886:web:f1f3b43ea3a6a5e9c034c7',
    messagingSenderId: '1002940114886',
    projectId: 'kidguard-fadf9',
    authDomain: 'kidguard-fadf9.firebaseapp.com',
    storageBucket: 'kidguard-fadf9.firebasestorage.app',
    measurementId: 'G-1SNSCM8XL8',
    databaseURL: firebaseRtdbUrl,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC91Z63QjQ3UT66BQJXri9gLDEY_Y0QlHQ',
    appId: '1:1002940114886:android:9195333d78a74111c034c7',
    messagingSenderId: '1002940114886',
    projectId: 'kidguard-fadf9',
    storageBucket: 'kidguard-fadf9.firebasestorage.app',
    databaseURL: firebaseRtdbUrl,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC91Z63QjQ3UT66BQJXri9gLDEY_Y0QlHQ',
    appId: '1:1002940114886:ios:974bedf44794363ac034c7',
    messagingSenderId: '1002940114886',
    projectId: 'kidguard-fadf9',
    storageBucket: 'kidguard-fadf9.firebasestorage.app',
    iosBundleId: 'com.example.kidguard',
    databaseURL: firebaseRtdbUrl,
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC91Z63QjQ3UT66BQJXri9gLDEY_Y0QlHQ',
    appId: '1:1002940114886:ios:974bedf44794363ac034c7',
    messagingSenderId: '1002940114886',
    projectId: 'kidguard-fadf9',
    storageBucket: 'kidguard-fadf9.firebasestorage.app',
    iosBundleId: 'com.example.kidguard',
    databaseURL: firebaseRtdbUrl,
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwf-g2AydH4u0QzGxiqdqMbIgkADSA4Uo',
    appId: '1:1002940114886:web:46bd656a5768f7f7c034c7',
    messagingSenderId: '1002940114886',
    projectId: 'kidguard-fadf9',
    authDomain: 'kidguard-fadf9.firebaseapp.com',
    storageBucket: 'kidguard-fadf9.firebasestorage.app',
    measurementId: 'G-6LSGFSJQQT',
    databaseURL: firebaseRtdbUrl,
  );
}
