// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Realtime Database URL (must match Firebase console → Realtime Database).
  static const String firebaseRtdbUrl = 'https://kidguard-fadf9-default-rtdb.firebaseio.com';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: 'APP-ID',
    messagingSenderId: 'ID',
    projectId: 'YOUR-PROJECT-ID',
    authDomain: 'AUTH-DOMAIN',
    storageBucket: 'BUCKET',
    measurementId: 'MEASUREMENT-ID',
    databaseURL: firebaseRtdbUrl,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: 'APP-ID',
    messagingSenderId:'ID',
    projectId: 'YOUR-PROJECT-ID',
    storageBucket: 'BUCKET',
    databaseURL: firebaseRtdbUrl,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: 'APP-ID',
    messagingSenderId: 'ID',
    projectId: 'YOUR-PROJECT-ID',
    storageBucket: 'BUCKET',
    iosBundleId: 'BUNDEL-ID',
    databaseURL: firebaseRtdbUrl,
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: 'APP-ID',
    messagingSenderId: 'ID',
    projectId: 'YOUR-PROJECT-ID',
    storageBucket: 'BUCKET',
    iosBundleId: 'BUNDEL-ID',
    databaseURL: firebaseRtdbUrl,
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: 'APP-ID',
    messagingSenderId: 'ID',
    projectId: 'YOUR-PROJECT-ID',
    authDomain: 'AUTH-DOMAIN',
    storageBucket: 'BUCKET-ID',
    measurementId: 'MEASUREMENT-ID',
    databaseURL: firebaseRtdbUrl,
  );
}
